set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 10

set -g status-position bottom
set -g status-style "bg=default,fg=white"
set -g window-status-current-style "bold"
set -g status-left "#[bold] #S "
set -g status-right " %Y-%m-%d %H:%M "

setw -g mode-keys vi

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
bind f display-popup -E -w 85% -h 85% "tmux-sessionizer"
bind w display-popup -E -w 85% -h 85% "tmux-worktree"

bind -r H resize-pane -L 5
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 5
